/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#fafafa', 100: '#f5f5f5', 200: '#e5e5e5', 300: '#d4d4d4',
          400: '#a3a3a3', 500: '#737373', 600: '#525252', 700: '#404040',
          800: '#262626', 900: '#171717', 950: '#0a0a0a',
        },
        'p-accent':      'var(--accent)',
        'p-accent-hover':'var(--accent-hover)',
        'p-accent-subtle':'var(--accent-subtle)',
        'p-surface':     'var(--bg-card)',
        'p-surface-alt': 'var(--bg-card-alt)',
        'p-app':         'var(--bg-app)',
        'p-layer':       'var(--bg-layer)',
        'p-nav':         'var(--bg-nav)',
        'p-control':     'var(--bg-control)',
        'p-text':        'var(--text-primary)',
        'p-text-2':      'var(--text-secondary)',
        'p-text-3':      'var(--text-tertiary)',
        'p-border':      'var(--border)',
        'p-border-strong':'var(--border-strong)',
      },
      fontFamily: {
        ui: ['var(--ui-font)', 'system-ui', 'sans-serif'],
        sans: ['var(--ui-font)', 'system-ui', 'sans-serif'],
        mono: ['var(--ui-font-mono)', 'monospace'],
      },
      fontSize: {
        'ui-caption': ['var(--font-size-caption)', { lineHeight: '16px' }],
        'ui-body':    ['var(--font-size-body)', { lineHeight: 'var(--line-height-body)' }],
        'ui-subtitle':['var(--font-size-subtitle)', { lineHeight: '28px' }],
        'ui-title':   ['var(--font-size-title)', { lineHeight: '32px' }],
        xs:   ['12px', { lineHeight: '16px' }],
        sm:   ['13px', { lineHeight: '20px' }],
        base: ['14px', { lineHeight: '20px' }],
        lg:   ['16px', { lineHeight: '24px' }],
        xl:   ['20px', { lineHeight: '28px' }],
        '2xl':['24px', { lineHeight: '32px' }],
        '3xl':['30px', { lineHeight: '36px' }],
      },
      borderRadius: {
        'ui':    'var(--r-md)',
        'ui-sm': 'var(--r-sm)',
        'ui-lg': 'var(--r-lg)',
        'ui-xl': 'var(--r-xl)',
        DEFAULT: 'var(--r-md)',
        sm:  'var(--r-sm)',
        md:  'var(--r-md)',
        lg:  'var(--r-lg)',
        xl:  'var(--r-xl)',
        '2xl': 'var(--r-2xl)',
        full: '9999px',
      },
      boxShadow: {
        'ui-sm': 'var(--shadow-sm)',
        'ui-md': 'var(--shadow-md)',
        'ui-lg': 'var(--shadow-lg)',
        'ui-xl': 'var(--shadow-xl)',
        card:  'var(--shadow-sm)',
        dialog:'var(--shadow-xl)',
      },
      spacing: {
        '4.5': '18px', '13': '52px', '15': '60px', '18': '72px',
      },
      height: {
        'app-header': 'var(--header-h)',
        'ui-control': '36px',
        ribbon: '80px',
        'status-bar': '32px',
        'tab-bar': 'var(--tabbar-h)',
        'title-bar': '32px',
      },
      width: { sidebar: 'var(--nav-width)' },
      transitionDuration: {
        fast:   'var(--dur-fast)',
        normal: 'var(--dur-normal)',
      },
      transitionTimingFunction: {
        ui: 'var(--ease)',
      },
      animation: {
        'fade-in':  'fadeIn 200ms var(--ease)',
        'scale-in': 'scaleIn 150ms var(--ease)',
        'slide-up': 'slideUp 200ms var(--ease)',
      },
      keyframes: {
        fadeIn:  { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        scaleIn: { '0%': { transform: 'scale(0.95)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        slideUp: { '0%': { transform: 'translateY(8px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
