// @quizforge/types — Shared Zod schemas + TypeScript types
// Single source of truth for all data structures

// Quiz schemas
export {
    // Question types
    QuestionTypeSchema,
    type QuestionType,
    MediaTypeSchema,
    type MediaType,
    MediaSchema,
    type Media,
    FeedbackModeSchema,
    type FeedbackMode,
    FeedbackSchema,
    type Feedback,
    BaseQuestionSchema,

    // Question type schemas
    TrueFalseQuestionSchema,
    type TrueFalseQuestion,
    MultipleChoiceOptionSchema,
    type MultipleChoiceOption,
    MultipleChoiceQuestionSchema,
    type MultipleChoiceQuestion,
    MultipleResponseQuestionSchema,
    type MultipleResponseQuestion,
    BlankSchema,
    type Blank,
    FillInBlankQuestionSchema,
    type FillInBlankQuestion,
    MatchingDisplayModeSchema,
    type MatchingDisplayMode,
    MatchingPairSchema,
    type MatchingPair,
    MatchingQuestionSchema,
    type MatchingQuestion,
    SequenceItemSchema,
    type SequenceItem,
    SequenceQuestionSchema,
    type SequenceQuestion,
    WordBankSlotSchema,
    type WordBankSlot,
    WordBankWordSchema,
    type WordBankWord,
    WordBankQuestionSchema,
    type WordBankQuestion,
    HotspotShapeSchema,
    type HotspotShape,
    HotspotSchema,
    type Hotspot,
    ClickMapQuestionSchema,
    type ClickMapQuestion,
    ShortEssayQuestionSchema,
    type ShortEssayQuestion,
    BlankPageSchema,
    type BlankPage,

    // Union question type
    QuestionSchema,
    type Question,

    // Quiz config
    SubmissionModeSchema,
    type SubmissionMode,
    QuizSettingsSchema,
    type QuizSettings,
    QuizResultSettingsSchema,
    type QuizResultSettings,
    QuizInformationSchema,
    type QuizInformation,
    ProtectionModeSchema,
    type ProtectionMode,
    QuizUserSchema,
    type QuizUser,
    QuizSecuritySchema,
    type QuizSecurity,
    ProgressStyleSchema,
    type ProgressStyle,
    NavigationStyleSchema,
    type NavigationStyle,
    ThemeSchema,
    type Theme,

    // Full quiz
    QuizSchema,
    type Quiz,
    QuizSummarySchema,
    type QuizSummary,

    // Student
    StudentSchema,
    type Student,
    StudentListSchema,
    type StudentList,

    // .qfz
    QfzManifestSchema,
    type QfzManifest,
} from './quiz'

// Result & network schemas
export {
    QuestionResultSchema,
    type QuestionResult,
    SubmittedViaSchema,
    type SubmittedVia,
    QuizResultSchema,
    type QuizResult,
    ValidationResultSchema,
    type ValidationResult,
    HeartbeatSchema,
    type Heartbeat,
    TabOutEventSchema,
    type TabOutEvent,
    StudentStatusSchema,
    type StudentStatus,
    MonitorStudentSchema,
    type MonitorStudent,
    ServerInfoSchema,
    type ServerInfo,
    ExportResultSchema,
    type ExportResult,
    AppSettingsSchema,
    type AppSettings,
} from './result'
